version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm run watch"
    env_file:
      - .env
      - .env-for-test
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - redis
  redis:
    image: "redis:3.2.11-alpine"
    volumes:
      - ./tmp/redis/data:/data
